Presenter and Data Binding
htmlacademy-ecmascript/1593103-big-trip-15 pull request #10
Opened 2021-08-23 22:30 UTC by bsgribtmfu

2021-08-24 17:59 UTC, Shramkoweb requested changes

2021-08-24 17:59 UTC, Shramkoweb commented on package.json
> +    "nanoid": "3.1.25",
Зафиксировал версию - держи лайк ))

2021-08-24 17:59 UTC, Shramkoweb commented on src/presenter/event.js
> +    remove(prevEventComponent);     // this._element = null AND remove element from DOM
Думаю можно одним комментарием подытожить этот блок удаления сверху.

2021-08-24 17:59 UTC, Shramkoweb commented on src/presenter/event.js
> +    document.addEventListener('keydown', this._escKeyDownHandler); // вешаем ф-ю обработчик нажатия клавиши esc
Ты все таки или на русс или на анг пиши коментарии =)

2021-08-24 17:59 UTC, Shramkoweb commented on src/utils/common.js
> +  if (index === -1) {
Если не нашли - то вернем весь массив? Хм, странно. Я бы возвращал что-то другое null или undefined.

2021-08-24 17:59 UTC, Shramkoweb commented on src/utils/common.js
> +  if (index === -1) {
Просто как мне потом снаружи, когда использую `updateItem` понять, что ничего обновить не удалось? Ведь и так и так я получаю снаружи массив - в итоге не ясно он обновился или остался исходный.

2021-08-24 17:59 UTC, Shramkoweb commented on src/utils/common.js
> +  if (index === -1) {
В общем надо подумать))

2021-08-24 17:59 UTC, Shramkoweb commented on src/utils/render.js
> +    oldChild = oldChild.getElement();
Мутировать параметр ф-и плохо. Создавай переменные внутри и не мутируй

2021-08-24 17:59 UTC, Shramkoweb commented on src/utils/render.js
> +const remove = (component) => {
remove чего?)) Просто удалить?

2021-08-24 18:26 UTC, bsgribtmfu commented on src/utils/common.js
> +  if (index === -1) {
если мы вернем null или undefined, то ничего не отрендерится

2021-08-24 18:30 UTC, bsgribtmfu commented on src/utils/render.js
> +const remove = (component) => {
эта функция удаляет как ссылку на dom-узел в презентере так и сам элемет из dom. эта функция кстати не моя, а скопирована по совету лектора.

2021-08-24 19:15 UTC, bsgribtmfu commented on src/utils/render.js
> +    oldChild = oldChild.getElement();
а там не просто так мутируют, погляди на эту функцию.

2021-08-24 19:37 UTC, Shramkoweb commented on src/utils/render.js
> +    oldChild = oldChild.getElement();
Ответил в телеге. Можно обойтись без мутаций))

2021-08-24 19:37 UTC, Shramkoweb commented on src/utils/render.js
> +const remove = (component) => {
removeElement  думаю будет ок

2021-08-25 05:52 UTC, Shramkoweb approved these changes

2021-08-25 05:52 UTC, merged