Module6 task1
htmlacademy-ecmascript/1593103-big-trip-15 pull request #12
Opened 2021-08-31 15:57 UTC by bsgribtmfu

draft

2021-09-01 23:36 UTC, bsgribtmfu commented on src/view/event.js
> +const generateCheckedOffers = (offers) => { // дописать логику проверка на checked
кстати, ума не приложу как это сделать, эта вьюха же ничего не знает про chekecked элементы у вьюхи рекдактирования формы

2021-09-04 15:03 UTC, bsgribtmfu commented
@Shramkoweb

2021-09-05 15:23 UTC, Shramkoweb requested changes

2021-09-05 15:23 UTC, Shramkoweb commented on src/mock/data-structure.js
> +    description: generateTitle(DESCRIPTION),
👍

2021-09-05 15:23 UTC, Shramkoweb commented on src/mock/data-structure.js
> +const generateDistanations = () => CITIES.map((city) => Object.assign({}, generateDistanation(), {name: city}));
generateDistanations - должна принимать CITIES как параметр. А не брать его с окружения, чистая ф-я. Вроде не раз обсуждали))

2021-09-05 15:23 UTC, Shramkoweb commented on src/mock/data-structure.js
> +  TYPES.forEach((type) => {
Аналогично TYPES как параметр

2021-09-05 15:23 UTC, Shramkoweb commented on src/view/Smart.js
> +  updateData(update, justDataUpdating) {
update - это что? Данные которые апдейтим?

2021-09-05 15:23 UTC, Shramkoweb commented on src/view/Smart.js
> +  updateData(update, justDataUpdating) {
justDataUpdating - это старые данные?

2021-09-05 15:23 UTC, Shramkoweb commented on src/view/edit-form.js
> +export default class EditForm extends Smart { // название классов с заглавной буквы?
ДА

2021-09-05 15:23 UTC, Shramkoweb commented on src/view/edit-form.js
> +  reset(event) {
ресет - по сути приводит даннные к исходнуму виду через парсер?

2021-09-05 15:23 UTC, Shramkoweb commented on src/view/edit-form.js
> +    if (!price || price === 0) {
!price можно будет обмануть пустыми пробелами. Делай сразу .trim и потом проверяй на длину

2021-09-05 17:24 UTC, bsgribtmfu commented on src/view/edit-form.js
> +  reset(event) {
да, все верно, он берет то состояние которые

2021-09-05 17:28 UTC, bsgribtmfu commented on src/mock/data-structure.js
> +  TYPES.forEach((type) => {
Это мне надо взять эту константу, закинуть в новую переменную, потом передать имя это переменной функции, и так везде, сейчас там будет куча ненужного кода, ну хз, я понимаю что такое чистые функции, но я эти файлы удалю через 2 дня.

2021-09-05 17:33 UTC, bsgribtmfu commented on src/view/edit-form.js
> +    if (!price || price === 0) {
мое регулярное выражение не дает ввести ничего кроме цифр, а с условием где я использую свойство trim моя форма ввода ведет себя странно.

2021-09-05 18:53 UTC, Shramkoweb commented on src/mock/data-structure.js
> +  TYPES.forEach((type) => {
Еще доп переменную не  надо создавать. Эта константа станет просто параметром ф-и и все.

2021-09-05 18:53 UTC, Shramkoweb commented on src/view/edit-form.js
> +    if (!price || price === 0) {
Это не важно. Фунция ничего не знает про регулярку. Она работает со строкой и строка может быть не коррекстной

2021-09-05 18:53 UTC, merged