changed the function of calculating the time of one event, added date…
htmlacademy-ecmascript/1593103-big-trip-15 pull request #13
Opened 2021-09-05 23:34 UTC by bsgribtmfu

… picker functionality with Flatpickr

2021-09-05 23:44 UTC, bsgribtmfu commented on src/utils/date.js
> +const humanizeEventDurationDate = (date) => {
пришлось поменять функционал отображения времени продолжительности события (см. видео в тг).

2021-09-05 23:44 UTC, bsgribtmfu commented on src/utils/date.js
> +      if(date[key] !== 0 && key !== 'seconds' && key !== 'milliseconds') {
я здесь иттерирую обьект разницы date_from, date_to.
Данный обьект содержит следующую структуру:

```
{
years: 0,
months: 0,
days: 0,
hours: 3,
munutes, 28,
seconds, 0,
milliseconds, 0,
}
```
но иногда случается что seconds  и milliseconds не равны нулю (особенности метода duration у dayjs) и я решил временно добавить  проверку на эти единицы времени, тк по тз они не нужны.

2021-09-05 23:44 UTC, bsgribtmfu commented on src/view/edit-form.js
> +        // defaultDate: this._data.date_from,
надо ли указывать дату по умолчанию в обьекте настроек у flatpickr?

2021-09-06 19:22 UTC, Shramkoweb requested changes

2021-09-06 19:22 UTC, Shramkoweb commented on src/utils/common.js
> +const getFirstLetter = (key) => key.split('')[0].toUpperCase();
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt лучше вот - как раз твойслучай и по семантике более верно

2021-09-06 19:22 UTC, Shramkoweb commented on src/utils/date.js
> +const humanizeEventDurationDate = (date) => {
??

2021-09-06 19:22 UTC, Shramkoweb commented on src/utils/date.js
> +      if(date[key] !== 0 && key !== 'seconds' && key !== 'milliseconds') {
ок

2021-09-06 19:22 UTC, Shramkoweb commented on src/view/edit-form.js
> +        ['time_24hr']: true,
Зачем тут кавычки?

2021-09-06 19:22 UTC, Shramkoweb commented on src/view/edit-form.js
> +        // defaultDate: this._data.date_from,
Пускай будет текущая дата - да

2021-09-06 19:22 UTC, Shramkoweb commented on src/view/edit-form.js
> +        ['time_24hr']: true,
Кавычки

2021-09-06 19:22 UTC, Shramkoweb commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
// eslint-disable-line ??

2021-09-06 19:22 UTC, Shramkoweb commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
Тут массива прилетает и ты сразу достаешь dateFrom?

2021-09-06 20:52 UTC, bsgribtmfu commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
а как надо? почему я не могу достать сразу переменную?

2021-09-06 21:02 UTC, bsgribtmfu commented on src/utils/date.js
> +const humanizeEventDurationDate = (date) => {
отправил, но я уже решил эту проблему, можно оставить без комметариев.)

2021-09-06 21:47 UTC, Shramkoweb commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
Нормаотно, но мне не нравиться, что ты вырубаешь линетр. Зачем?

2021-09-06 21:47 UTC, Shramkoweb commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
Линтер

2021-09-06 21:57 UTC, bsgribtmfu commented on src/view/edit-form.js
> +  _startDateChangeHandler([dateFrom]) { // eslint-disable-line
а он ругался на весь метод, с чем это связано я не знаю, ошибка не гуглится, ну я и закомитил, кстати, не поверишь, пять минут назад он самостоятельно прекратил ругаться. :D

2021-09-06 22:19 UTC, Shramkoweb approved these changes

2021-09-06 22:19 UTC, Shramkoweb commented
Я потом линтер чекну на допуске.

2021-09-06 22:19 UTC, merged