generation of mock data
htmlacademy-ecmascript/1593103-big-trip-15 pull request #4
Opened 2021-08-07 16:32 UTC by bsgribtmfu

2021-08-07 19:30 UTC, bsgribtmfu commented
I will fix it soon..

2021-08-07 23:14 UTC, bsgribtmfu commented
¯\_(ツ)_/¯

2021-08-07 23:17 UTC, bsgribtmfu commented
https://user-images.githubusercontent.com/70964880/128616052-b1131a57-0ec2-4895-a0bc-33fecb2fada6.mov

У меня встречается множество разных форматов:
```
YYYY-MM-DD
MMM DD
DD/MM/YY
HH:MM
MM
HH
```

2021-08-08 07:55 UTC, Shramkoweb requested changes

2021-08-08 07:55 UTC, Shramkoweb commented on package.json
> +    "dayjs": "^1.10.6"
Устанавливаем только фиксированные версии зависимостей. Без `^`

`npm  i -E some-deps-name`

2021-08-08 07:55 UTC, Shramkoweb commented on src/main.js
>  };
Дубаю рендер функция - утилитарная и не завязана на модуль main. Можно вынести в отдельный utils.js модуль

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/constans.js
> +const PRICE = [180, 90, 50, 30, 170, 50, 130];
Массивы именуем как множество prices

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/constans.js
> +const BASEPRICE = [282, 1100, 630, 380, 450];
Составные слова через нижний прочерк + это массив (множество). 
BASE_PRICES

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/constans.js
> +const IMAGEDESCRIPTION = [
СОСТАВНЫЕ_ИМЕНА =)

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/generate-task.js
> +import dayjs from 'dayjs';
Обычно в модулях сразу идет импорт бибилиотек. Потом локально твои модули

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/generate-task.js
> +const generateOffers = (titles, price) => {
Тоже сюда параметром число, сколько офферов генерировать. Хорошо, когда ф-я чистая и идемпотентная

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/generate-task.js
> +      'src': `http://picsum.photos/248/152?r=${randomIndex}`,
Картинки пофиксились? Я помню ты говорил не работало?

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/generate-task.js
> +  const description = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id orci
Пока оставим так, но на реальном проекте было бы гдето в константах тоже

2021-08-08 07:55 UTC, Shramkoweb commented on src/mock/generate-task.js
> +  return randomTitles.join(' ');
Нормально что join без точки? Мы же джойним абзацы верно?)

2021-08-08 07:55 UTC, Shramkoweb commented on src/utils.js
> +  max = Math.floor(max);
Плохо менять что-то прям в параметрах функции. Заведи под это отдельные переменные внутри функции и в них ложи, то что пришло в ф-ю

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/edit-form.js
> +const getLastWord = (offer) => { // может эту ф-ю закинуть в utils.js ?
+

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/edit-form.js
> +  const pucturesElements = pictures.map((picture) => `<img class="event__photo" src="${picture.src}" alt=${picture.description}">`);
Я бы сделал это ф-й, а не значением сразу от `pictures`

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/edit-form.js
> +const genarateOffers = (offers) => {
genarateOffers - у нас уже гдето бы была, для данных. Тут я вижу отрисовку, а не герацию. 
renderOffers

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/event.js
> +
Что это такое и зачем оно ?

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/event.js
> +const differenceDate = (dateFrom, dateTo) => { // может эту ф-ю закинуть в utils.js ?
Утиль

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/event.js
> +
Чтобы потом можно сравнивать длительность?

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/event.js
> +  const { title: offerTitle, price: offerPrice } = offer;
Зачем тут при деструкторизации меняешь имя? Оно вроде и так адекватное?

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/trip-info.js
> +const findPoints = (points) => { // может эту ф-ю закинуть в utils.js ?
А что она делает обьясни?

2021-08-08 07:55 UTC, Shramkoweb commented on src/view/trip-info.js
> +  const costValueDefinition = points
просто имя для константы cost?

2021-08-08 15:28 UTC, bsgribtmfu commented on src/view/event.js
> +
> Что это такое и зачем оно ?

это наверное своеобразная инициализация плагина, duration - это плагин. Без этого не работает.

2021-08-08 16:04 UTC, bsgribtmfu commented on src/mock/generate-task.js
> +const generateOffers = (titles, price) => {
по домашнему заданию это число рандомное, число генерируется на 7 строке.

2021-08-08 16:07 UTC, bsgribtmfu commented on src/mock/generate-task.js
> +  return randomTitles.join(' ');
это пробел между предложениями. по домашнему заданию я беру рандомное число предложений (от 1 до 5) из абцаца и генерируют на основании этого описание города.

2021-08-08 16:14 UTC, bsgribtmfu commented on src/view/trip-info.js
> +const findPoints = (points) => { // может эту ф-ю закинуть в utils.js ?
она возвращает обьект на основании которого мы рисуем компоненту tripInfo (17 строка)

2021-08-08 16:16 UTC, bsgribtmfu commented on src/view/trip-info.js
> +  const costValueDefinition = points
`  const costValueDefinition = points
    .map((point) => point.base_price)
    .reduce((sum, price) => sum + price);
`

2021-08-08 16:17 UTC, bsgribtmfu commented on src/view/trip-info.js
> +  const costValueDefinition = points
не понял вопрос.
`  const costValueDefinition = points
                                                   .map((point) => point.base_price)
                                                   .reduce((sum, price) => sum + price);`

2021-08-08 16:18 UTC, bsgribtmfu commented on src/view/trip-info.js
> +  const costValueDefinition = points
`  const costValueDefinition = points.map((point) => point.base_price).reduce((sum, price) => sum + price);`

2021-08-08 16:21 UTC, bsgribtmfu commented on src/view/event.js
> +  const { title: offerTitle, price: offerPrice } = offer;
хотел явно обозначить что это именно заголовок "предложений".

2021-08-08 16:22 UTC, bsgribtmfu commented on src/view/edit-form.js
> +  const pucturesElements = pictures.map((picture) => `<img class="event__photo" src="${picture.src}" alt=${picture.description}">`);
ну хз ...

2021-08-08 16:23 UTC, bsgribtmfu commented on src/utils.js
> +  max = Math.floor(max);
так вроде так и сделано) кстати эта функция от ### MDN Web Docs

2021-08-08 17:33 UTC, Shramkoweb commented
>  2021-08-08.00.57.49.mov 
> У меня встречается множество разных форматов:
> 
> ```
> YYYY-MM-DD
> MMM DD
> DD/MM/YY
> HH:MM
> MM
> HH
> ```
> 
> Что будем делать?

Создать как на видео ф-ю которая являеться абстракцией над dayjs. Это функция будет принимать дату которую надо форматировать и формат во что.

2021-08-08 17:34 UTC, Shramkoweb commented on src/utils.js
> +  max = Math.floor(max);
Нет, так не сделано. min = Math.ceil(min) это переприсваивание новго значение в парамтр ф-и. 
const min = Math.ceil(min). Вот это будет правильно

2021-08-08 17:34 UTC, Shramkoweb commented on src/view/edit-form.js
> +  const pucturesElements = pictures.map((picture) => `<img class="event__photo" src="${picture.src}" alt=${picture.description}">`);
почему?

2021-08-08 17:34 UTC, Shramkoweb commented on src/view/event.js
> +
Пускай будет тут.

2021-08-08 18:02 UTC, Shramkoweb commented on src/view/trip-info.js
> +  const costValueDefinition = points
Я понимаю, почему имени cost недостаточно тут?

2021-08-08 18:02 UTC, Shramkoweb commented on src/view/trip-info.js
> +const findPoints = (points) => { // может эту ф-ю закинуть в utils.js ?
Расчет обьекта маршрута поездки - на английском будет не findPoints как у тебя называеться ф-я. 

Если она генерирует обьект маршрута, то так и нывай ф-ю. А то она делает одно, но называеться совсем по другому =)

2021-08-09 06:53 UTC, Shramkoweb approved these changes

2021-08-09 06:53 UTC, Shramkoweb commented on src/utils.js
> +  return dayjs.duration(to.diff(from)).format();
Почему тут появился .format() ?

2021-08-09 06:53 UTC, Shramkoweb commented on src/utils.js
> +const humanizeTaskDate = (date, format) => dayjs(date).format(format);
humanize**Task**Date - Task было в учебном проекте, потому что там задачи - у нас же нет задачи. 

Лучше такие ф-и именовать абстрактно без привязки к бизнес логикии проекта. 

Функция форматирования даты - что в проекте с карточками, что в проекте с музыкой будет называться одинаково.

2021-08-09 06:53 UTC, merged

2021-08-13 16:08 UTC, bsgribtmfu commented on src/utils.js
> +  return dayjs.duration(to.diff(from)).format();
потому что на 30 строке я возвращал строку, а метод format() делает из этого Date. Так с ходу и не вспомню зачем я это делал. )