class-based component development, added event handler functions
htmlacademy-ecmascript/1593103-big-trip-15 pull request #5
Opened 2021-08-11 14:30 UTC by bsgribtmfu

2021-08-12 20:15 UTC, Shramkoweb requested changes

2021-08-12 20:15 UTC, Shramkoweb commented on src/main.js
> +// import { editForm } from './view/edit-form.js';
Мусор - убираем))

2021-08-12 20:15 UTC, Shramkoweb commented on src/main.js
> +    // eventItem.removeElement(); // не работает :(
Что тут работает, а что нет?))

2021-08-12 20:15 UTC, Shramkoweb commented on src/main.js
> +  };
В утиль

2021-08-12 20:15 UTC, Shramkoweb commented on src/main.js
> +  editFormComponent.getElement().addEventListener('submit', (evt) => {
Пока ок - потом будет в классах отдельно это жить))

2021-08-12 20:15 UTC, Shramkoweb commented on src/main.js
> +  pointsObject.map((point) => {
Странные имена - где-то наша точка - это поинт, а где-то ивент)) Надо все таки решить на будущее

2021-08-12 20:15 UTC, Shramkoweb commented on src/view/event.js
> +          <time class="event__start-time" datetime="${humanizeTaskDate(dateFrom, 'YYYY-MM-DD')}">${humanizeTaskDate(dateFrom, 'HH:MM')}</time>
humanizeTaskDate - у нас не задачи)) Задачи былы в учебном проекте))

2021-08-12 20:15 UTC, Shramkoweb commented on src/view/event.js
> +          <time class="event__start-time" datetime="${humanizeTaskDate(dateFrom, 'YYYY-MM-DD')}">${humanizeTaskDate(dateFrom, 'HH:MM')}</time>
где у нас Task?))

2021-08-12 20:15 UTC, Shramkoweb commented on src/view/navigation.js
> +const generateNavigation = () => (
Где-то ф-я которая возвращает верстку называеться generate, a где-то create =)
Приведи в общему виду =)

2021-08-13 16:00 UTC, bsgribtmfu commented on src/main.js
> +  };
блин, я буквально в следующем задании это должен удалить, а в util я не могу без костылей вынести, смотри сколько мне нужно будет передавать аргументов в эту ф-ю. (53 строка)

2021-08-13 16:12 UTC, bsgribtmfu commented on src/main.js
> +  };
запушу без этого, надеюсь прокатит :D

2021-08-14 16:16 UTC, Shramkoweb approved these changes
LGTM =)

2021-08-14 16:16 UTC, merged